### ISSUE TITLE
Authentication failed with incorrect password

### ISSUE THREAD

**Issue by lykmapipo** [lykmapipo/irina#2]
When athenticating user withe correct `email` authenticationField but incorrect password I experience the below stacktrace

``` javascript
node_modules/irina/lib/morphs/authenticable.js:241
                        authenticable.failedAttempts + 1;
                                     ^
TypeError: Cannot read property 'failedAttempts' of undefined
    at node_modules/irina/lib/morphs/authenticable.js:241:38
    at node_modules/irina/lib/morphs/authenticable.js:139:21
    at node_modules/irina/node_modules/bcryptjs/dist/bcrypt.js:230:13
    at node_modules/irina/node_modules/bcryptjs/dist/bcrypt.js:1167:21
    at Object.next [as _onImmediate] (node_modules/irina/node_modules/bcryptjs/dist/bcrypt.js:1047:21)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by lykmapipo** [comment]
Fixed on [commit](https://github.com/lykmapipo/irina/commit/e7c0f7dcd7399c54e9720cdd33704dd9d2ce8f9a)
